compile:
	javac *.java

run_random:
	java ReversiGame Human vs RandomComputer

run_intelligent:
	java ReversiGame Human vs IntelligentComputer

run_human:
	java ReversiGame Human vs Human

run_randomvintelligent:
	java ReversiGame RandomComputer vs IntelligentComputer

run_randomvrandom:
	java ReversiGame RandomComputer vs RandomComputer

run_intelligentvintelligent:
	java ReversiGame IntelligentComputer vs IntelligentComputer

clean:
	rm *.class

